#!/bin/bash

#PBS -A PCON0003
#PBS -N fit_rayleigh
#PBS -l walltime=00:20:00
#PBS -l nodes=1:ppn=40
#PBS -o /fs/scratch/PAS0654/ara/10pct/Rayleigh/err_out_logs
#PBS -e /fs/scratch/PAS0654/ara/10pct/Rayleigh/err_out_logs
gi
source /users/PAS0654/osu0673/A23_analysis_new2/env.sh

cd $TMPDIR
pbsdcp /fs/scratch/PAS0654/ara/10pct/Rayleigh/output_files/merged.root .
touch commandfile
for bin in {0..512}
do
	line="/users/PAS0654/osu0673/A23_analysis_new2/AraRoot/analysis/a23_analysis_programs/other/rayleigh/fit_rayleigh merged.root 0 $bin"
	echo ${line}>>commandfile
done

module load pcp
mpiexec parallel-command-processor commandfile

pbsdcp $TMPDIR/*.png /users/PAS0654/osu0673/A23_analysis_new2/AraRoot/analysis/a23_analysis_programs/other/rayleigh/fits/
